[package]
name = "cmpdfmt"
version = "0.1.0"
authors = ["mwc10 <43445389+mwc10@users.noreply.github.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
structopt = "0.2.14"
csv = "1.0.5"
walkdir = "2.2.7"
log = "0.4.6"
flexi_logger = "0.10.5"
sd3 = { path = "../sd3" }
