[package]
name = "units"
version = "0.1.0"
authors = ["mwc10 <43445389+mwc10@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0.84"
failure = "0.1.5"
test_utils = { path = "../test_utils" }
